### ISSUE TITLE
Add Uppercase keywords

### ISSUE THREAD

**Issue by austinbarberrepo** [piotrgredowski/poor-mans-t-sql-formatter-vscode-extension#10]
Is there a way to manually add keywords on format? Like for example I'd like to update rtrim and count to be RTRIM and COUNT when formatting the selction?

Thank you!

**Comment by piotrgredowski** [comment]
@nocomputeruser 
so for example:
you would like to select ONLY word `rtrim`, run formatter, and have `RTRIM` as a result?
edit: After second read I think I get it.
So you would like to specify additional words which should be treated as keywords, yes?

**Comment by austinbarberrepo** [comment]
Sorry for the late response. Yes, I would like to add additional words as keywords. So like I would highlight the whole selection that needs to be formatted and then it would treat rtrim as a keyword to make uppercase. Sorry not the best at explaing things!
