### ISSUE TITLE
"poor-mans-t-sql-formatter-pg.expectedLanguages" option error

### ISSUE THREAD

**Issue by filat0ff** [piotrgredowski/poor-mans-t-sql-formatter-vscode-extension#11]
Extension not work in matched languages. Full format and format selection, both not work.

**Comment by piotrgredowski** [comment]
@filat0ff can you paste your version of VSCode?

**Comment by filat0ff** [comment]
@piotrgredowski  Version of VSCode - 1.72.2

**Comment by filat0ff** [comment]
I think problem on 8 line of extension.js. 
Extension first check which language in current document. And then launch "formatDocument" where is the extension parameter "expectedLanguages"checking. If launch extension with non-sql document, then "expectedLanguages" parameter will not be checked.

**Comment by piotrgredowski** [comment]
@filat0ff I think it should work as expected now (in up to 10 minutes 0.1.5 version should be published)
Please try and let me know.

**Comment by filat0ff** [comment]
Great, it works! Thank you!
