### ISSUE TITLE
If code is selected and file is saved, it replaces entire document with selection

### ISSUE THREAD

**Issue by benzdouglas** [piotrgredowski/poor-mans-t-sql-formatter-vscode-extension#4]
Hi there, I've started to have an issue where if I happen to have something selected and I save the file, it will replace the entire file with just the code that is selected. Had a coworker try it on their machine and they had the same problem. Removed the extension and the problem went away, added it back and the problem returned. Any ideas for how to solve?

**Comment by piotrgredowski** [comment]
Formatting code selection is not working properly. I'd try to look at it till the end of the week.

**Comment by benzdouglas** [comment]
Thanks for fixing that so fast! It's adding a paragraph now whenever code is selected, but that is a whole lot better than replacing the entire document and I can live with it

**Comment by piotrgredowski** [comment]
I found out that I fixed it wrong :) I will fix properly in some short time.

**Comment by piotrgredowski** [comment]
@benzdouglas I think now everything should be fine. [v0.1.1](https://marketplace.visualstudio.com/items?itemName=piotrgredowski.poor-mans-t-sql-formatter-pg&ssr=false#overview) was already published in VSCode marketplace, so you should be able to check if it's working. Happy coding ;)

**Comment by benzdouglas** [comment]
Works! Thanks again!
