### ISSUE TITLE
Question about formatting on save

### ISSUE THREAD

**Issue by austinbarberrepo** [piotrgredowski/poor-mans-t-sql-formatter-vscode-extension#9]
Is there a way to preserve new lines on save? I can't tell if this is a vscode issue or a formatter extension request? Basically when I hit save it removes empty lines that I would like to keep. I have this extension saved as the default formatter for SQL files.

Thank you!

**Comment by piotrgredowski** [comment]
@abarber229 Hi. Can you paste here code before save and after? I mean - how it looks before formatter formats it ;)

**Comment by austinbarberrepo** [comment]
So I usually have a multi-line comment block up at the beginning. Then I like to then have a line or two between the comment block and the start of the query. Just seems a bit cleaner to me. The top is what I have before save. When I hit save, it then looks like the bottom one. I'm okay with the syntax formatting. Just would like to be able to add line breaks when needed without them getting overwritten. I also have a quick snippets tab usually open that I reference. I've found that if I put a semi-colon at the end, it will allow me to have a line break. If I don't have a semi-colon then it will remove the line break. Thanks for the help/assistance. 

BEFORE SAVE
```
/*
	.SYNOPSIS
	Adds a file name extension to a supplied name.
	
	.AUTHOR
	Insert who created the script.

	.DESCRIPTION
	Adds a file name extension to a supplied name.
	Takes any strings for the file name or extension.

	.LINK
	Online version: http://www.fabrikam.com/extension.html

	.LAST Modified
	Insert date when script was last modified. 
	
	.NOTES
	Put notes here.
*/

SELECT * FROM column_name

```
AFTER SAVE
```
/*
	.SYNOPSIS
	Adds a file name extension to a supplied name.
	
	.AUTHOR
	Insert who created the script.

	.DESCRIPTION
	Adds a file name extension to a supplied name.
	Takes any strings for the file name or extension.

	.LINK
	Online version: http://www.fabrikam.com/extension.html

	.LAST Modified
	Insert date when script was last modified. 
	
	.NOTES
	Put notes here.
*/
SELECT *
FROM column_name
```

BEFORE SAVE
```
-- Get logdate data greater from 30 days from today.
WHERE logdate >= DATEADD(day, - 30, GETDATE());

-- Get logdate data greater from 1 month from today.
WHERE logdate >= DATEADD(month, - 1, GETDATE());

-- Get logdate data greater from 1 year from today.
WHERE logdate >= DATEADD(year, - 1, GETDATE());

-- Get data starting from 30 days ago on a field value.
SELECT DATEADD(day, - 30, logdate) AS logdate;
```

AFTER SAVE
```
-- Get logdate data greater from 30 days from today.
WHERE logdate >= DATEADD(day, - 30, GETDATE())
-- Get logdate data greater from 1 month from today.
WHERE logdate >= DATEADD(month, - 1, GETDATE())
-- Get logdate data greater from 1 year from today.
WHERE logdate >= DATEADD(year, - 1, GETDATE())

-- Get data starting from 30 days ago on a field value.
SELECT DATEADD(day, - 30, logdate) AS logdate;
```

**Comment by piotrgredowski** [comment]
@abarber229 
The issue you are reporting - I can't fix it for you :(.
Extension I've created is just to be able to use tool called "Poor Man's T-SQL Formatter" directly in VSCode. It uses under the hood [external npm library which is responsible for formatting code](https://www.npmjs.com/package/poor-mans-t-sql-formatter). 

There are some options you can try to play with to achieve what you want - test these options here: https://poorsql.com/
Then these options can be specified for this VSCode extension also - `CTRL + , (settings)` and then filter with `poor-mans`.

I'm closing your issue with this comment. Sorry for not being able to help - but yeah :) for now this VSCode extension uses external library.
